### ISSUE TITLE
Why the rebranding?

### ISSUE THREAD

**Issue by normanlolx** [mortola/behat-seo-contexts#1]
Glad I found the package again, thought it was lost forever.

It was initially named novecode/behat-website-contexts, right?

Keep up the good work!

**Comment by marcortola** [comment]
I changed the package name because I thought it could be more self-explanatory. The main purpose of this Mink extension is to help in SEO testing (mortola/behat-seo-contexts), not in general website testing (novecode/behat-website-contexts).

I'm sorry for any inconveniences... and thank you for your words!

**Comment by normanlolx** [comment]
That sounds reasonable. Thanks for taking the time to explain!
